name: Deploy to Pi on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run deploy script locally on the Pi
        run: bash /home/pi/deployElecInv.sh
